spring:
  application:
    name: can-feign
  cloud:
    discovery:
      client:
        simple:
          instances:
            book:
              - uri: http://localhost:8081
    openfeign:
      circuitbreaker:
        enabled: true